server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DIB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false # t?t truy v?n c? s? d? li?u m?i khi k?t th�c request
    hibernate:
      ddl-auto: validate # validate: ki?m tra thu?c t�nh d? li?u.
    properties:
      hibernate:
        # SQL8 support this
        #        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
